/**
 * 网址列表
 * time 2012-02-12
 */

KISSY.add("app/sitemap", function(S){

    var sitemap = [
        {   
            "first": true,
            "nav" : "热门导航",
            "cnt" : [
                {"title" : "百　度", "url" : "http://www.baidu.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/baidu.com.png"},
                {"title" : "新　浪", "url" : "http://www.sina.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/sina.com.cn.png"},
                {"title" : "腾　讯", "url" : "http://www.qq.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/qq.com.png"},
                {"title" : "搜　狐", "url" : "http://www.sohu.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/sohu.com.png"},
                {"title" : "网　易", "url" : "http://www.163.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/163.com.png"},
                {"title" : "新浪微博", "url" : "http://weibo.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/weibo.com.png"},
                {"title" : "淘宝网", "url" : "http://www.taobao.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/taobao.com.png"},
                {"title" : "天猫", "url" : "http://www.tmall.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/tmall.com.png"},
                {"title" : "京东", "url" : "http://click.union.360buy.com/JdClick/?unionId=19370&t=1&to=http://www.360buy.com", "img": "http://kiwiobjects.b0.upaiyun.com/a/jd.com.png"},
                {"title" : "亚马逊", "url" : "http://www.amazon.cn/?_encoding=UTF8&tag=345502059-23&linkCode=ur2&camp=536&creative=3200", "img": "http://kiwiobjects.b0.upaiyun.com/a/amazon.cn.png"},
                {"title" : "支付宝", "url" : "http://www.alipay.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/alipay.com.png"},
                {"title" : "土豆网", "url" : "http://www.tudou.com", "img": "http://kiwiobjects.b0.upaiyun.com/a/tudou.com.png"},
                {"title" : "优酷网", "url" : "http://www.youku.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/youku.com.png"},
                {"title" : "58同城", "url" : "http://www.58.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/58.com.png"},
                {"title" : "爱奇艺", "url" : "http://www.iqiyi.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/iqiyi.com.png"}
            ]
        },
        {   
            "nav" : "视频",
            "cnt" : [
                {"title" : "优酷网", "url" : "http://www.youku.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/youku.com.png"},
                {"title" : "土豆网", "url" : "http://www.tudou.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/tudou.com.png"},
                {"title" : "搜狐视频", "url" : "http://tv.sohu.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/tv.sohu.com.png"},
                {"title" : "腾讯视频", "url" : "http://v.qq.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/v.qq.com.png"},
                {"title" : "新浪视频", "url" : "http://video.sina.com.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/video.sina.com.cn.png"},
                {"title" : "酷6网", "url" : "http://www.ku6.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/ku6.com.png"},
                {"title" : "56网", "url" : "http://www.56.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/56.com.png"},
                {"title" : "激动网", "url" : "http://www.joy.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/joy.cn.png"},
                {"title" : "爱奇艺", "url" : "http://www.iqiyi.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/iqiyi.com.png"},
                {"title" : "凤凰视频", "url" : "http://v.ifeng.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/v.ifeng.com.png"},
                {"title" : "PPTV", "url" : "http://www.pptv.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/cool.pptv.com.png"},
                {"title" : "迅雷看看", "url" : "http://www.xunlei.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/xunlei.com.png"},
                {"title" : "PPS", "url" : "http://www.pps.tv/", "img": "http://kiwiobjects.b0.upaiyun.com/a/pps.tv.png"},
                {"title" : "暴风影音", "url" : "http://baofeng.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/gaoqing.baofeng.com.png"},
                {"title" : "CNTV", "url" : "http://www.cntv.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/cntv.cn.png"},
                {"title" : "芒果tv", "url" : "http://www.imgo.tv/", "img": "http://kiwiobjects.b0.upaiyun.com/a/imgo.tv.png"},
                {"title" : "m1905", "url" : "http://www.m1905.com/vod/", "img": "http://kiwiobjects.b0.upaiyun.com/a/m1905.com.png"},
                {"title" : "乐视网", "url" : "http://www.letv.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/letv.com.png"},
                {"title" : "360影视", "url" : "http://v.360.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/v.360.cn.png"},
                {"title" : "六间房", "url" : "http://www.6.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/6.cn.png"}
            ]
        },
        {   
            "nav" : "新闻",
            "cnt" : [
                {"title" : "新浪新闻", "url" : "http://news.sina.com.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/sina.com.cn.png"},
                {"title" : "腾讯新闻", "url" : "http://news.qq.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/qq.com.png"},
                {"title" : "凤凰资讯", "url" : "http://news.ifeng.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/ifeng.com.png"},
                {"title" : "搜狐新闻", "url" : "http://news.sohu.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/sohu.com.png"},
                {"title" : "网易新闻", "url" : "http://news.163.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/163.com.png"},
                {"title" : "财经网", "url" : "http://www.caixin.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/caixin.com.png"},
                {"title" : "南方周末", "url" : "http://www.infzm.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/infzm.com.png"},
                {"title" : "联合早报", "url" : "http://www.zaobao.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/zaobao.com.png"},
                {"title" : "环球网", "url" : "http://www.huanqiu.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/huanqiu.com.png"},
                {"title" : "央视网", "url" : "http://www.cntv.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/cntv.cn.png"},
                {"title" : "新华网", "url" : "http://www.xinhuanet.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/xinhuanet.com.png"},
                {"title" : "人民网", "url" : "http://www.people.com.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/people.com.cn.png"},
                {"title" : "国际在线", "url" : "http://gb.cri.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/gb.cri.cn.png"},
                {"title" : "半月谈", "url" : "http://www.banyuetan.org/", "img": "http://kiwiobjects.b0.upaiyun.com/a/banyuetan.org.png"},
                {"title" : "光明网", "url" : "http://www.gmw.cn/", "img": "http://kiwiobjects.b0.upaiyun.com/a/gmw.cn.png"},
                {"title" : "BBC", "url" : "http://www.bbc.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/bbc.com.png"},
                {"title" : "路透中文网", "url" : "http://cn.reuters.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/cn.reuters.com.png"},
                {"title" : "FT中文网", "url" : "http://www.ftchinese.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/ftchinese.com.png"},
                {"title" : "纽约时报", "url" : "http://www.infzm.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/nytimes.com.png"},
                {"title" : "国家地理", "url" : "http://ngm.nationalgeographic.com/", "img": "http://kiwiobjects.b0.upaiyun.com/a/ngm.nationalgeographic.com.png"}
            ]
        },
        {   
            "nav" : "购物",
            "cnt" : [
                {"title" : "淘宝网", "url" : "http://www.taobao.com/go/chn/tbk_channel/channelcode.php?pid=mm_16596457_2494158_9488014&eventid=101329"},
                {"title" : "淘宝商城", "url" : "http://s.click.taobao.com/t_9?p=mm_16596457_2494158_9488024&l=http%3A%2F%2Fwww.tmall.com"},
                {"title" : "京东商城", "url" : "http://click.union.360buy.com/JdClick/?unionId=19370&t=1&to=http://www.360buy.com"},
                {"title" : "当当网", "url" : "http://union.dangdang.com/transfer.php?from=P-297808&ad_type=10&sys_id=1&backurl=http://www.dangdang.com/"},
                {"title" : "卓越亚马逊", "url" : "http://www.amazon.cn/?_encoding=UTF8&tag=345502059-23&linkCode=ur2&camp=536&creative=3200"},
                {"title" : "凡客诚品", "url" : "http://www.vancl.com?source=wolongxzg"},
                {"title" : "拍拍网", "url" : "http://www.paipai.com/"},
                {"title" : "阿里巴巴", "url" : "http://china.alibaba.com/"},
                {"title" : "新蛋网", "url" : "http://www.newegg.com.cn/?cm_mmc=CPS-_-wolongxzg-_-wolongxzg-_-eventcode"},
                {"title" : "好乐买", "url" : "http://www.okbuy.com?from=trackingid_wolongxzg-23453"},
                {"title" : "乐淘网", "url" : "http://www.letao.com/?source=wolongxzg"},
                {"title" : "一号店", "url" : "http://www.yihaodian.com/product/index.do?tracker_u=1052697570&merchant=1"},
                {"title" : "麦考林", "url" : "http://www.m18.com/"},
                {"title" : "淘鞋网", "url" : "http://www.taoxie.cn/"},
                {"title" : "逛街网", "url" : "http://www.togj.com/"},
                {"title" : "梦芭莎", "url" : "http://shopping.moonbasa.com/rd/rd.aspx?a_id=mbs&other=wolongxzg&url=http://www.moonbasa.com/"},
                {"title" : "时尚起义", "url" : "http://www.shishangqiyi.com/"},
                {"title" : "麦包包", "url" : "http://www.mbaobao.com/"},
                {"title" : "乐蜂网", "url" : "http://www.lafaso.com/"},
                {"title" : "尚品网", "url" : "http://www.shangpin.com/"},
                {"title" : "慧聪网", "url" : "http://www.hc360.com/"},
                {"title" : "易趣网", "url" : "http://www.eachnet.com/"},
                {"title" : "百货网", "url" : "http://www.baihuo.com/"},
                {"title" : "孔夫子", "url" : "http://www.kongfz.com/"},
                {"title" : "拉手网", "url" : "http://www.lashou.com/"},
                {"title" : "美　团", "url" : "http://r.union.meituan.com/url/visit/?a=1&key=1fKEZh0rec5FVUHjNnaqDi8xvXuR7Ygb&url=http://www.meituan.com"},
                {"title" : "24券", "url" : "http://www.24quan.com/"},
                {"title" : "团宝网", "url" : "http://www.groupon.cn/"},
                {"title" : "糯米网", "url" : "http://www.nuomi.com/"},
                {"title" : "58团购", "url" : "http://t.58.com/"},
                {"title" : "大众点评团", "url" : "http://t.dianping.com/"},
                {"title" : "高朋团购", "url" : "http://www.gaopeng.com/"},
                {"title" : "F　团", "url" : "http://www.ftuan.com/"},
                {"title" : "窝窝团", "url" : "http://www.55tuan.com/"},
                {"title" : "聚划算", "url" : "http://ju.taobao.com/"},
                {"title" : "满座网", "url" : "http://www.manzuo.com/"},
                {"title" : "爽　团", "url" : "http://www.shuangtuan.com/"},
                {"title" : "米奇网", "url" : "http://www.miqi.cn/"},
                {"title" : "爱帮团", "url" : "http://tuan.aibang.com/"},
                {"title" : "美丽说", "url" : "http://www.meilishuo.com/tuan/"},
                {"title" : "可可团", "url" : "http://www.cocotuan.com/"},
                {"title" : "犀利团", "url" : "http://www.xilituan.com/"},
            ]
        },
        {   
            "nav" : "体育",
            "cnt" : [
                {"title" : "新浪体育", "url" : "http://sports.sina.com.cn/"},
                {"title" : "搜狐体育", "url" : "http://sports.sohu.com/"},
                {"title" : "腾讯体育", "url" : "http://sports.qq.com/"},
                {"title" : "网易体育", "url" : "http://sports.163.com/"},
                {"title" : "TOM体育", "url" : "http://sports.tom.com/"},
                {"title" : "雅虎体育", "url" : "http://sports.cn.yahoo.com/"},
                {"title" : "ESPN中文网", "url" : "http://www.espnstar.com.cn/"},
                {"title" : "cctv5", "url" : "http://sports.cntv.cn/"},
                {"title" : "直播吧", "url" : "http://www.zhibo8.com/"},
                {"title" : "凤凰体育", "url" : "http://news.ifeng.com/sports/"},
                {"title" : "华体网", "url" : "http://www.sportscn.com/"},
                {"title" : "体坛周报", "url" : "http://www.titan24.com/"},
                {"title" : "NBA中国", "url" : "http://china.nba.com/"},
                {"title" : "新浪NBA", "url" : "http://sports.sina.com.cn/nba/"},
                {"title" : "腾讯NBA", "url" : "http://sports.qq.com/nba/"},
                {"title" : "网易NBA", "url" : "http://sports.163.com/nba/"},
                {"title" : "搜狐NBA", "url" : "http://sports.sohu.com/nba.shtml"},
                {"title" : "中国篮协", "url" : "http://www.cba.gov.cn/"},
                {"title" : "新浪足球", "url" : "http://sports.sina.com.cn/global/"},
                {"title" : "搜狐足球", "url" : "http://sports.sohu.com/guojizuqiu.shtml"},
                {"title" : "腾讯足球", "url" : "http://sports.qq.com/isocce/"},
                {"title" : "ESPN足球", "url" : "http://www.espnstar.com.cn/new/international/"},
                {"title" : "网易足球", "url" : "http://sports.163.com/world/"},
                {"title" : "天下足球网", "url" : "http://www.qxzqw.com/"}
            ]
        },
        {   
            "nav" : "游戏",
            "cnt" : [
                {"title" : "4399小游戏", "url" : "http://www.4399.com/"},
                {"title" : "7K7K小游戏", "url" : "http://www.7k7k.com/"},
                {"title" : "3366小游戏", "url" : "http://www.3366.com/"},
                {"title" : "2144小游戏", "url" : "http://www.2144.cn/"},
                {"title" : "007小游戏", "url" : "http://www.yx007.com/"},
                {"title" : "3839小游戏", "url" : "http://www.3839.com/"},
                {"title" : "洛克王国", "url" : "http://17roco.qq.com/"},
                {"title" : "赛尔号", "url" : "http://www.51seer.com/"},
                {"title" : "奥拉星", "url" : "http://www.9aola.com/"},
                {"title" : "摩尔庄园", "url" : "http://www.51mole.com/"},
                {"title" : "龙斗士", "url" : "http://www.9lds.com/"},
                {"title" : "奥雅之光", "url" : "http://www.9aoya.com/"},
                {"title" : "穿越火线", "url" : "http://cf.qq.com/"},
                {"title" : "地下城与勇士", "url" : "http://dnf.qq.com/"},
                {"title" : "七雄争霸", "url" : "http://7.qq.com/"},
                {"title" : "英雄之城", "url" : "http://yxzc.qq.com/"},
                {"title" : "烽火战国", "url" : "http://zg.qq.com/"},
                {"title" : "英雄联盟", "url" : "http://lol.qq.com/"},
                {"title" : "冒险岛", "url" : "http://mxd.sdo.com/"},
                {"title" : "热血传奇", "url" : "http://mir2.sdo.com/"},
                {"title" : "彩虹岛", "url" : "http://chd.sdo.com/homepage.asp"},
                {"title" : "仙境传说", "url" : "http://ro.sdo.com/"},
                {"title" : "龙之谷", "url" : "http://dn.sdo.com/"},
                {"title" : "苍天OL", "url" : "http://ct.sdo.com/"},
                {"title" : "劲舞团", "url" : "http://mg.9you.com/"},
                {"title" : "仙剑奇侠传", "url" : "http://xj.9you.com/"},
                {"title" : "神兵传奇", "url" : "http://sc.9you.com/"},
                {"title" : "光线飞车", "url" : "http://rc.9you.com/"},
                {"title" : "宠物森林", "url" : "http://mf.9you.com/"},
                {"title" : "流星蝴蝶剑", "url" : "http://lx.9you.com/"},
                {"title" : "梦幻西游", "url" : "http://xyq.163.com/"},
                {"title" : "大唐无双", "url" : "http://dt2.163.com/"},
                {"title" : "天下3", "url" : "http://tx3.163.com/"},
                {"title" : "魔兽世界", "url" : "http://www.warcraftchina.com/"},
                {"title" : "倩女幽魂OL", "url" : "http://qn.163.com/"},
                {"title" : "藏宝阁", "url" : "http://cbg.163.com/"},
                {"title" : "梦幻诛仙", "url" : "http://xmhzx.wanmei.com/"},
                {"title" : "完美世界", "url" : "http://world2.wanmei.com/"},
                {"title" : "口袋西游", "url" : "http://kdxy.wanmei.com/"},
                {"title" : "赤壁", "url" : "http://chibi.wanmei.com/"},
                {"title" : "神鬼传奇", "url" : "http://sgcq.wanmei.com/"},
                {"title" : "降龙之剑", "url" : "http://xlzj.wanmei.com/"},
            ]
        },
        {   
            "nav" : "音乐",
            "cnt" : [
                {"title" : "虾　米", "url" : "http://www.xiami.com/"},
                {"title" : "巨　鲸", "url" : "http://www.top100.cn/"},
                {"title" : "酷　我", "url" : "http://mbox.kuwo.cn/"},
                {"title" : "百度MP3", "url" : "http://mp3.baidu.com/"},
                {"title" : "ting!", "url" : "http://ting.baidu.com/"},
                {"title" : "QQ音乐", "url" : "http://music.qq.com/"},
                {"title" : "酷　狗", "url" : "http://www.kugou.com/"},
                {"title" : "九　天", "url" : "http://www.9sky.com/"},
                {"title" : "DJ嗨嗨", "url" : "http://www.djkk.com/"},
                {"title" : "深港DJ", "url" : "http://www.ik123.com/"},
                {"title" : "DJ音乐厅", "url" : "http://www.hcdj.com/"},
                {"title" : "DJ527", "url" : "http://www.dj527.com/"},
                {"title" : "音悦台", "url" : "http://www.yinyuetai.com/"},
                {"title" : "优酷音乐", "url" : "http://music.youku.com/"},
                {"title" : "土豆音乐", "url" : "http://music.tudou.com/"},
                {"title" : "酷6音乐", "url" : "http://mv.ku6.com/"},
                {"title" : "百度音乐MV", "url" : "http://video.baidu.com/childchannal/videomv/videomv.html"},
                {"title" : "奇艺音乐", "url" : "http://www.qiyi.com/yinyue/"},
                {"title" : "儿童专辑", "url" : "http://list.mp3.baidu.com/top/shaoergequ.html"},
                {"title" : "经典老歌", "url" : "http://mp3.baidu.com/m?f=ms&rf=idx&tn=baidump3&ct=134217728&lf=&rn=&word=%BE%AD%B5%E4%C0%CF%B8%E8&lm=-1&rf=bangdang#1"},
                {"title" : "影视金曲", "url" : "http://list.mp3.baidu.com/top/movie.html"},
                {"title" : "轻音乐", "url" : "http://list.mp3.baidu.com/top/qingyinyue.html"},
                {"title" : "网络歌曲", "url" : "http://mp3.baidu.com/m?f=ms&rf=idx&tn=baidump3&ct=134217728&lf=&rn=&word=%CD%F8%C2%E7%B8%E8%C7%FA&lm=-1rf=bangdang#1"},
                {"title" : "日韩流行", "url" : "http://list.mp3.baidu.com/top/rihan.html"},
                {"title" : "音乐之声", "url" : "http://musicradio.cnr.cn/"},
                {"title" : "豆瓣电台", "url" : "http://douban.fm/"},
                {"title" : "青檬音悦台", "url" : "http://www.911pop.com/"},
                {"title" : "多米音乐", "url" : "http://www.duomi.com/"},
                {"title" : "亦　歌", "url" : "http://www.1g1g.com/"},
                {"title" : "新浪乐库", "url" : "http://music.sina.com.cn/yueku/"}
            ]
        },
        {   
            "nav" : "极客",
            "cnt" : [
                {"title" : "Engadget", "url" : "http://cn.engadget.com/"},
                {"title" : "爱极客", "url" : "http://www.igeek.com.cn/"},
                {"title" : "36氪", "url" : "http://www.36kr.com/"},
                {"title" : "互动中国", "url" : "http://www.damndigital.com/"},
                {"title" : "cnbeta", "url" : "http://www.cnbeta.com/"},
                {"title" : "远景", "url" : "http://www.pcbeta.com/"},
                {"title" : "麦根", "url" : "http://nmag.cn/"},
                {"title" : "极客公园", "url" : "http://event.geekpark.net/"},
                {"title" : "动点科技", "url" : "http://cn.technode.com/"},
                {"title" : "Tech2IPO", "url" : "http://tech2ipo.com/"},
                {"title" : "爱PC", "url" : "http://www.ipc.me/"},
                {"title" : "威锋网", "url" : "http://www.weiphone.com/"},
                {"title" : "云诺", "url" : "http://www.yun.io/"}

            ]
        }
    ];

    return sitemap;
});