/**
 * 网址列表
 * time 2012-02-12
 * create wangjian	wolongxzg@gmail.com
 */
website = [
	{	
		'cat' : '热门导航',
		'class' : 'common', 
		'cnt' : [
			{'name' : '百　度', 'url' : 'http://www.baidu.com/'},
			{'name' : '新　浪', 'url' : 'http://www.sina.com/'},
			{'name' : '腾　讯', 'url' : 'http://www.qq.com/'},
			{'name' : '搜　狐', 'url' : 'http://www.sohu.com/'},
			{'name' : '网　易', 'url' : 'http://www.163.com/'},
			{'name' : '谷　歌', 'url' : 'http://www.google.com.hk/'},
			{'name' : '凤凰网', 'url' : 'http://www.ifeng.com/'},
			{'name' : '新华网', 'url' : 'http://www.baidu.com/'},
			{'name' : '人民网', 'url' : 'http://www.people.com.cn/'},
			{'name' : '联合早报', 'url' : 'http://www.zaobao.com/'},
			{'name' : 'CNTV', 'url' : 'http://www.cntv.cn/index.shtml'},
			{'name' : '环球网', 'url' : 'http://www.huanqiu.com/'},
			{'name' : '淘宝网', 'url' : 'http://www.taobao.com/'},
			{'name' : '淘宝商城', 'url' : 'http://s.click.taobao.com/t_9?p=mm_16596457_2494158_9488024&l=http%3A%2F%2Fwww.tmall.com'},
			{'name' : '京东商城', 'url' : 'http://www.360buy.com/'},
			{'name' : '当当网', 'url' : 'http://union.dangdang.com/transfer.php?from=P-297808&ad_type=10&sys_id=1&backurl=http://www.dangdang.com/'},
			{'name' : '卓越亚马逊', 'url' : 'http://www.amazon.cn/?_encoding=UTF8&tag=345502059-23&linkCode=ur2&camp=536&creative=3200'},
			{'name' : '凡客诚品', 'url' : 'http://www.vancl.com?source=wolongxzg'},
			{'name' : '新浪微博', 'url' : 'http://weibo.com/'},
			{'name' : '人人网', 'url' : 'http://www.renren.com/'},
			{'name' : '开心网', 'url' : 'http://www.kaixin001.com/'},
			{'name' : '豆　瓣', 'url' : 'http://www.douban.com/'},
			{'name' : 'QQ空间', 'url' : 'http://qzone.qq.com/'},
			{'name' : '天涯社区', 'url' : 'http://www.tianya.cn/'},
			{'name' : '优酷网', 'url' : 'http://www.youku.com/'},
			{'name' : '土豆网', 'url' : 'http://www.tudou.com/'},
			{'name' : '酷6网', 'url' : 'http://www.ku6.com/'},
			{'name' : '56网', 'url' : 'http://www.56.com/'},
			{'name' : '激动网', 'url' : 'http://www.joy.cn/'},
			{'name' : '奇艺网', 'url' : 'http://www.qiyi.com/'},
			{'name' : '赶集网', 'url' : 'http://www.ganji.com/'},
			{'name' : '58同城', 'url' : 'http://www.58.com'},
			{'name' : '中关村在线', 'url' : 'http://www.zol.com.cn/'},
			{'name' : '太平洋电脑', 'url' : 'http://www.pconline.com.cn/'},
			{'name' : '汽车之家', 'url' : 'http://www.autohome.com.cn/'},
			{'name' : '智联招聘', 'url' : 'http://www.zhaopin.com/'},
			{'name' : '虾　米', 'url' : 'http://www.xiami.com/'},
			{'name' : '巨　鲸', 'url' : 'http://www.top100.cn/'},
			{'name' : '豆瓣电台', 'url' : 'http://douban.fm/'},
			{'name' : '音悦TV', 'url' : 'http://www.yinyuetai.com/'},
			{'name' : 'ting!', 'url' : 'http://ting.baidu.com/'},
			{'name' : 'QQ音乐', 'url' : 'http://music.qq.com/'}
		]
	},
	{	
		'cat' : '视频',
		'class' : 'video', 
		'cnt' : [
			{'name' : '优酷网', 'url' : 'http://www.youku.com/'},
			{'name' : '土豆网', 'url' : 'http://www.tudou.com/'},
			{'name' : '酷6网', 'url' : 'http://www.ku6.com/'},
			{'name' : '56网', 'url' : 'http://www.56.com/'},
			{'name' : '激动网', 'url' : 'http://www.joy.cn/'},
			{'name' : '奇艺网', 'url' : 'http://www.qiyi.com/'},
			{'name' : '六间房', 'url' : 'http://v.6.cn/'},
			{'name' : '腾讯宽频', 'url' : 'http://v.qq.com/'},
			{'name' : '东方宽频', 'url' : 'http://www.smgbb.cn/'},
			{'name' : '新华视频', 'url' : 'http://www.news.cn/video/index.htm'},
			{'name' : '新浪播客', 'url' : 'http://video.sina.com.cn/index.shtml'},
			{'name' : '凤凰宽频', 'url' : 'http://v.ifeng.com/'},
			{'name' : 'PPTV', 'url' : 'http://www.pptv.com/'},
			{'name' : '迅雷看看', 'url' : 'http://www.xunlei.com/'},
			{'name' : 'PPS', 'url' : 'http://www.pps.tv/'},
			{'name' : 'UUsee', 'url' : 'http://www.uusee.com/'},
			{'name' : 'QQLive', 'url' : 'http://v.qq.com/index.html'},
			{'name' : '暴风影音', 'url' : 'http://gaoqing.baofeng.com/?s=Index-P720'},
			{'name' : '中国网络电视台', 'url' : 'http://www.cntv.cn/'},
			{'name' : '芒果tv', 'url' : 'http://www.imgo.tv/'},
			{'name' : '江苏卫视', 'url' : 'http://www.jstv.com/'},
			{'name' : '网易公开课', 'url' : 'http://open.163.com/'},
			{'name' : 'm1905电影网', 'url' : 'http://www.m1905.com/vod/'},
			{'name' : '乐视网', 'url' : 'http://www.letv.com/'}
		]
	},
	{	
		'cat' : '新闻',
		'class' : 'news', 
		'cnt' : [
			{'name' : '新浪新闻', 'url' : 'http://news.sina.com.cn/'},
			{'name' : '腾讯新闻', 'url' : 'http://news.qq.com/'},
			{'name' : '凤凰资讯', 'url' : 'http://news.ifeng.com/'},
			{'name' : 'CCTV新闻', 'url' : 'http://news.cntv.cn/'},
			{'name' : '搜狐新闻', 'url' : 'http://news.sohu.com/'},
			{'name' : '网易新闻', 'url' : 'http://news.163.com/'},
			{'name' : '中国网', 'url' : 'http://www.china.com.cn/'},
			{'name' : '新华网', 'url' : 'http://www.xinhuanet.com/'},
			{'name' : '人民网', 'url' : 'http://www.people.com.cn/'},
			{'name' : '联合早报', 'url' : 'http://www.zaobao.com/'},
			{'name' : '中国新闻网', 'url' : 'http://www.chinanews.com/'},
			{'name' : '中华网', 'url' : 'http://www.china.com/'},
			{'name' : '路透中文网', 'url' : 'http://cn.reuters.com/'},
			{'name' : '人民日报', 'url' : 'http://paper.people.com.cn/'},
			{'name' : '国际在线', 'url' : 'http://gb.cri.cn/'},
			{'name' : '半月谈', 'url' : 'http://www.banyuetan.org/'},
			{'name' : '光明网', 'url' : 'http://www.gmw.cn/'},
			{'name' : '南方网', 'url' : 'http://www.southcn.com/'},
			{'name' : '南方周末', 'url' : 'http://www.infzm.com/'},
			{'name' : '大公报', 'url' : 'http://www.takungpao.com/'},
			{'name' : '华商报', 'url' : 'http://hsb.hsw.cn/'},
			{'name' : '大河报', 'url' : 'http://www.dahe.cn/'},
			{'name' : '香港文汇报', 'url' : 'http://www.wenweipo.com/'},
			{'name' : '南风窗', 'url' : 'http://www.nfcmag.com/'},
			{'name' : '新京报', 'url' : 'http://www.bjnews.com.cn/'},
			{'name' : '羊城晚报', 'url' : 'http://www.ycwb.com/'},
			{'name' : '南方都市报', 'url' : 'http://nd.oeeee.com/'},
			{'name' : '中国新闻周刊', 'url' : 'http://www.inewsweek.cn/'},
			{'name' : '扬子晚报', 'url' : 'http://www.yangtse.com/'},
			{'name' : '中国评论新闻', 'url' : 'http://gb.chinareviewnews.com/'},
			{'name' : '朝鲜日报', 'url' : 'http://chn.chosun.com/'},
			{'name' : '俄罗斯之声', 'url' : 'http://www.ruvr.ru/index.php?lng=pek'},
			{'name' : '英国路透社', 'url' : 'http://www.reuters.com/'},
			{'name' : '联合国新闻', 'url' : 'http://www.un.org/chinese/News/'},
			{'name' : '美国CNN', 'url' : 'http://www.cnn.com/'},
			{'name' : '美国时代周刊', 'url' : 'http://www.time.com/'}
		]
	},
	{	
		'cat' : '购物',
		'class' : 'shopping', 
		'cnt' : [
			{'name' : '淘宝网', 'url' : 'http://www.taobao.com/'},
			{'name' : '淘宝商城', 'url' : 'http://s.click.taobao.com/t_9?p=mm_16596457_2494158_9488024&l=http%3A%2F%2Fwww.tmall.com'},
			{'name' : '京东商城', 'url' : 'http://www.360buy.com/'},
			{'name' : '当当网', 'url' : 'http://union.dangdang.com/transfer.php?from=P-297808&ad_type=10&sys_id=1&backurl=http://www.dangdang.com/'},
			{'name' : '卓越亚马逊', 'url' : 'http://www.amazon.cn/?_encoding=UTF8&tag=345502059-23&linkCode=ur2&camp=536&creative=3200'},
			{'name' : '凡客诚品', 'url' : 'http://www.vancl.com?source=wolongxzg'},
			{'name' : '拍拍网', 'url' : 'http://www.paipai.com/'},
			{'name' : '阿里巴巴', 'url' : 'http://china.alibaba.com/'},
			{'name' : '新蛋网', 'url' : 'http://www.newegg.com.cn/?cm_mmc=CPS-_-wolongxzg-_-wolongxzg-_-eventcode'},
			{'name' : '好乐买', 'url' : 'http://www.okbuy.com?from=trackingid_wolongxzg-23453'},
			{'name' : '乐淘网', 'url' : 'http://www.letao.com/?source=wolongxzg'},
			{'name' : '一号店', 'url' : 'http://www.yihaodian.com/product/index.do?tracker_u=1052697570&merchant=1'},
			{'name' : '麦考林', 'url' : 'http://www.m18.com/'},
			{'name' : '淘鞋网', 'url' : 'http://www.taoxie.cn/'},
			{'name' : '逛街网', 'url' : 'http://www.togj.com/'},
			{'name' : '梦芭莎', 'url' : 'http://www.moonbasa.com'},
			{'name' : '时尚起义', 'url' : 'http://www.shishangqiyi.com/'},
			{'name' : '麦包包', 'url' : 'http://www.mbaobao.com/'},
			{'name' : '乐蜂网', 'url' : 'http://www.lafaso.com/'},
			{'name' : '尚品网', 'url' : 'http://www.shangpin.com/'},
			{'name' : '慧聪网', 'url' : 'http://www.hc360.com/'},
			{'name' : '易趣网', 'url' : 'http://www.eachnet.com/'},
			{'name' : '百货网', 'url' : 'http://www.baihuo.com/'},
			{'name' : '孔夫子旧书网', 'url' : 'http://www.kongfz.com/'},
			{'name' : '拉手网', 'url' : 'http://www.lashou.com/'},
			{'name' : '美　团', 'url' : 'http://www.lashou.com/'},
			{'name' : '24券', 'url' : 'http://www.24quan.com/'},
			{'name' : '团宝网', 'url' : 'http://www.groupon.cn/'},
			{'name' : '糯米网', 'url' : 'http://www.nuomi.com/'},
			{'name' : '58团购', 'url' : 'http://t.58.com/'},
			{'name' : '大众点评团', 'url' : 'http://t.dianping.com/'},
			{'name' : '高朋团购', 'url' : 'http://www.gaopeng.com/'},
			{'name' : 'F　团', 'url' : 'http://www.ftuan.com/'},
			{'name' : '窝窝团', 'url' : 'http://www.55tuan.com/'},
			{'name' : '聚划算', 'url' : 'http://ju.taobao.com/'},
			{'name' : '满座网', 'url' : 'http://www.manzuo.com/'},
			{'name' : '爽　团', 'url' : 'http://www.baidu.com/'},
			{'name' : '米奇网', 'url' : 'http://www.shuangtuan.com/'},
			{'name' : '爱帮团', 'url' : 'http://tuan.aibang.com/'},
			{'name' : '美丽说', 'url' : 'http://www.meilishuo.com/tuan/'},
			{'name' : '可可团', 'url' : 'http://www.cocotuan.com/'},
			{'name' : '犀利团', 'url' : 'http://www.xilituan.com/'},
		]
	},
	{	
		'cat' : '体育',
		'class' : 'sport', 
		'cnt' : [
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
		]
	},
	{	
		'cat' : '热门导航',
		'class' : 'common', 
		'cnt' : [
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
		]
	},
	{	
		'cat' : '热门导航',
		'class' : 'common', 
		'cnt' : [
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
			{'name' : '百度', 'url' : 'http://www.baidu.com/'},
		]
	},
]



