/**
 * 网址列表
 * time 2012-02-12
 * create wangjian	wolongxzg@gmail.com
 */
xzgwebsite = [
	{	
		'cat' : '热门导航',
		'class' : 'xzg-common', 
		'cnt' : [
			{'name' : '百　度', 'url' : 'http://www.baidu.com/'},
			{'name' : '新　浪', 'url' : 'http://www.sina.com/'},
			{'name' : '腾　讯', 'url' : 'http://www.qq.com/'},
			{'name' : '搜　狐', 'url' : 'http://www.sohu.com/'},
			{'name' : '网　易', 'url' : 'http://www.163.com/'},
			{'name' : '谷　歌', 'url' : 'http://www.google.com.hk/'},
			{'name' : '凤凰网', 'url' : 'http://www.ifeng.com/'},
			{'name' : '新华网', 'url' : 'http://www.xinhuanet.com/'},
			{'name' : '人民网', 'url' : 'http://www.people.com.cn/'},
			{'name' : '联合早报', 'url' : 'http://www.zaobao.com/'},
			{'name' : 'CNTV', 'url' : 'http://www.cntv.cn/index.shtml'},
			{'name' : '环球网', 'url' : 'http://www.huanqiu.com/'},
			{'name' : '淘宝网', 'url' : 'http://www.taobao.com/go/chn/tbk_channel/channelcode.php?pid=mm_16596457_2494158_9488014&eventid=101329'},
			{'name' : '淘宝商城', 'url' : 'http://s.click.taobao.com/t_9?p=mm_16596457_2494158_9488024&l=http%3A%2F%2Fwww.tmall.com'},
			{'name' : '京东商城', 'url' : 'http://click.union.360buy.com/JdClick/?unionId=19370&t=1&to=http://www.360buy.com'},
			{'name' : '卓越亚马逊', 'url' : 'http://www.amazon.cn/?_encoding=UTF8&tag=345502059-23&linkCode=ur2&camp=536&creative=3200'},
			{'name' : '当当网', 'url' : 'http://union.dangdang.com/transfer.php?from=P-297808&ad_type=10&sys_id=1&backurl=http://www.dangdang.com/'},
			{'name' : '凡客诚品', 'url' : 'http://www.vancl.com?source=wolongxzg'},
			{'name' : '新浪微博', 'url' : 'http://weibo.com/'},
			{'name' : '人人网', 'url' : 'http://www.renren.com/'},
			{'name' : '开心网', 'url' : 'http://www.kaixin001.com/'},
			{'name' : '豆　瓣', 'url' : 'http://www.douban.com/'},
			{'name' : 'QQ空间', 'url' : 'http://qzone.qq.com/'},
			{'name' : '天涯社区', 'url' : 'http://www.tianya.cn/'},
			{'name' : '优酷网', 'url' : 'http://www.youku.com/'},
			{'name' : '土豆网', 'url' : 'http://www.tudou.com/'},
			{'name' : '酷6网', 'url' : 'http://www.ku6.com/'},
			{'name' : '56网', 'url' : 'http://www.56.com/'},
			{'name' : '激动网', 'url' : 'http://www.joy.cn/'},
			{'name' : '奇艺网', 'url' : 'http://www.qiyi.com/'},
			{'name' : '赶集网', 'url' : 'http://www.ganji.com/'},
			{'name' : '58同城', 'url' : 'http://www.58.com'},
			{'name' : '中关村在线', 'url' : 'http://www.zol.com.cn/'},
			{'name' : '太平洋电脑', 'url' : 'http://www.pconline.com.cn/'},
			{'name' : '汽车之家', 'url' : 'http://www.autohome.com.cn/'},
			{'name' : '智联招聘', 'url' : 'http://www.zhaopin.com/'},
			{'name' : '虾　米', 'url' : 'http://www.xiami.com/'},
			{'name' : '巨　鲸', 'url' : 'http://www.top100.cn/'},
			{'name' : '豆瓣电台', 'url' : 'http://douban.fm/'},
			{'name' : '音悦TV', 'url' : 'http://www.yinyuetai.com/'},
			{'name' : 'ting!', 'url' : 'http://ting.baidu.com/'},
			{'name' : 'QQ音乐', 'url' : 'http://music.qq.com/'}
		]
	},
	{	
		'cat' : '视频',
		'class' : 'xzg-video', 
		'cnt' : [
			{'name' : '优酷网', 'url' : 'http://www.youku.com/'},
			{'name' : '土豆网', 'url' : 'http://www.tudou.com/'},
			{'name' : '酷6网', 'url' : 'http://www.ku6.com/'},
			{'name' : '56网', 'url' : 'http://www.56.com/'},
			{'name' : '激动网', 'url' : 'http://www.joy.cn/'},
			{'name' : '奇艺网', 'url' : 'http://www.qiyi.com/'},
			{'name' : '六间房', 'url' : 'http://v.6.cn/'},
			{'name' : '腾讯宽频', 'url' : 'http://v.qq.com/'},
			{'name' : '东方宽频', 'url' : 'http://www.smgbb.cn/'},
			{'name' : '新华视频', 'url' : 'http://www.news.cn/video/index.htm'},
			{'name' : '新浪播客', 'url' : 'http://video.sina.com.cn/index.shtml'},
			{'name' : '凤凰宽频', 'url' : 'http://v.ifeng.com/'},
			{'name' : 'PPTV', 'url' : 'http://www.pptv.com/'},
			{'name' : '迅雷看看', 'url' : 'http://www.xunlei.com/'},
			{'name' : 'PPS', 'url' : 'http://www.pps.tv/'},
			{'name' : 'UUsee', 'url' : 'http://www.uusee.com/'},
			{'name' : 'QQLive', 'url' : 'http://v.qq.com/index.html'},
			{'name' : '暴风影音', 'url' : 'http://gaoqing.baofeng.com/?s=Index-P720'},
			{'name' : 'CNTV', 'url' : 'http://www.cntv.cn/'},
			{'name' : '芒果tv', 'url' : 'http://www.imgo.tv/'},
			{'name' : '江苏卫视', 'url' : 'http://www.jstv.com/'},
			{'name' : '网易公开课', 'url' : 'http://open.163.com/'},
			{'name' : 'm1905', 'url' : 'http://www.m1905.com/vod/'},
			{'name' : '乐视网', 'url' : 'http://www.letv.com/'}
		]
	},
	{	
		'cat' : '新闻',
		'class' : 'xzg-news', 
		'cnt' : [
			{'name' : '新浪新闻', 'url' : 'http://news.sina.com.cn/'},
			{'name' : '腾讯新闻', 'url' : 'http://news.qq.com/'},
			{'name' : '凤凰资讯', 'url' : 'http://news.ifeng.com/'},
			{'name' : 'CCTV新闻', 'url' : 'http://news.cntv.cn/'},
			{'name' : '搜狐新闻', 'url' : 'http://news.sohu.com/'},
			{'name' : '网易新闻', 'url' : 'http://news.163.com/'},
			{'name' : '中国网', 'url' : 'http://www.china.com.cn/'},
			{'name' : '新华网', 'url' : 'http://www.xinhuanet.com/'},
			{'name' : '人民网', 'url' : 'http://www.people.com.cn/'},
			{'name' : '联合早报', 'url' : 'http://www.zaobao.com/'},
			{'name' : '中国新闻网', 'url' : 'http://www.chinanews.com/'},
			{'name' : '中华网', 'url' : 'http://www.china.com/'},
			{'name' : '路透中文网', 'url' : 'http://cn.reuters.com/'},
			{'name' : '人民日报', 'url' : 'http://paper.people.com.cn/'},
			{'name' : '国际在线', 'url' : 'http://gb.cri.cn/'},
			{'name' : '半月谈', 'url' : 'http://www.banyuetan.org/'},
			{'name' : '光明网', 'url' : 'http://www.gmw.cn/'},
			{'name' : '南方网', 'url' : 'http://www.southcn.com/'},
			{'name' : '南方周末', 'url' : 'http://www.infzm.com/'},
			{'name' : '大公报', 'url' : 'http://www.takungpao.com/'},
			{'name' : '华商报', 'url' : 'http://hsb.hsw.cn/'},
			{'name' : '大河报', 'url' : 'http://www.dahe.cn/'},
			{'name' : '香港文汇报', 'url' : 'http://www.wenweipo.com/'},
			{'name' : '南风窗', 'url' : 'http://www.nfcmag.com/'},
			{'name' : '新京报', 'url' : 'http://www.bjnews.com.cn/'},
			{'name' : '羊城晚报', 'url' : 'http://www.ycwb.com/'},
			{'name' : '南方都市报', 'url' : 'http://nd.oeeee.com/'},
			{'name' : '中国新闻周刊', 'url' : 'http://www.inewsweek.cn/'},
			{'name' : '扬子晚报', 'url' : 'http://www.yangtse.com/'},
			{'name' : '中国评论新闻', 'url' : 'http://gb.chinareviewnews.com/'},
			{'name' : '朝鲜日报', 'url' : 'http://chn.chosun.com/'},
			{'name' : '俄罗斯之声', 'url' : 'http://www.ruvr.ru/index.php?lng=pek'},
			{'name' : '英国路透社', 'url' : 'http://www.reuters.com/'},
			{'name' : '联合国新闻', 'url' : 'http://www.un.org/chinese/News/'},
			{'name' : '美国CNN', 'url' : 'http://www.cnn.com/'},
			{'name' : '时代周刊', 'url' : 'http://www.time.com/'}
		]
	},
	{	
		'cat' : '购物',
		'class' : 'xzg-shopping', 
		'cnt' : [
			{'name' : '淘宝网', 'url' : 'http://www.taobao.com/go/chn/tbk_channel/channelcode.php?pid=mm_16596457_2494158_9488014&eventid=101329'},
			{'name' : '淘宝商城', 'url' : 'http://s.click.taobao.com/t_9?p=mm_16596457_2494158_9488024&l=http%3A%2F%2Fwww.tmall.com'},
			{'name' : '京东商城', 'url' : 'http://click.union.360buy.com/JdClick/?unionId=19370&t=1&to=http://www.360buy.com'},
			{'name' : '当当网', 'url' : 'http://union.dangdang.com/transfer.php?from=P-297808&ad_type=10&sys_id=1&backurl=http://www.dangdang.com/'},
			{'name' : '卓越亚马逊', 'url' : 'http://www.amazon.cn/?_encoding=UTF8&tag=345502059-23&linkCode=ur2&camp=536&creative=3200'},
			{'name' : '凡客诚品', 'url' : 'http://www.vancl.com?source=wolongxzg'},
			{'name' : '拍拍网', 'url' : 'http://www.paipai.com/'},
			{'name' : '阿里巴巴', 'url' : 'http://china.alibaba.com/'},
			{'name' : '新蛋网', 'url' : 'http://www.newegg.com.cn/?cm_mmc=CPS-_-wolongxzg-_-wolongxzg-_-eventcode'},
			{'name' : '好乐买', 'url' : 'http://www.okbuy.com?from=trackingid_wolongxzg-23453'},
			{'name' : '乐淘网', 'url' : 'http://www.letao.com/?source=wolongxzg'},
			{'name' : '一号店', 'url' : 'http://www.yihaodian.com/product/index.do?tracker_u=1052697570&merchant=1'},
			{'name' : '麦考林', 'url' : 'http://www.m18.com/'},
			{'name' : '淘鞋网', 'url' : 'http://www.taoxie.cn/'},
			{'name' : '逛街网', 'url' : 'http://www.togj.com/'},
			{'name' : '梦芭莎', 'url' : 'http://shopping.moonbasa.com/rd/rd.aspx?a_id=mbs&other=wolongxzg&url=http://www.moonbasa.com/'},
			{'name' : '时尚起义', 'url' : 'http://www.shishangqiyi.com/'},
			{'name' : '麦包包', 'url' : 'http://www.mbaobao.com/'},
			{'name' : '乐蜂网', 'url' : 'http://www.lafaso.com/'},
			{'name' : '尚品网', 'url' : 'http://www.shangpin.com/'},
			{'name' : '慧聪网', 'url' : 'http://www.hc360.com/'},
			{'name' : '易趣网', 'url' : 'http://www.eachnet.com/'},
			{'name' : '百货网', 'url' : 'http://www.baihuo.com/'},
			{'name' : '孔夫子', 'url' : 'http://www.kongfz.com/'},
			{'name' : '拉手网', 'url' : 'http://www.lashou.com/'},
			{'name' : '美　团', 'url' : 'http://r.union.meituan.com/url/visit/?a=1&key=1fKEZh0rec5FVUHjNnaqDi8xvXuR7Ygb&url=http://www.meituan.com'},
			{'name' : '24券', 'url' : 'http://www.24quan.com/'},
			{'name' : '团宝网', 'url' : 'http://www.groupon.cn/'},
			{'name' : '糯米网', 'url' : 'http://www.nuomi.com/'},
			{'name' : '58团购', 'url' : 'http://t.58.com/'},
			{'name' : '大众点评团', 'url' : 'http://t.dianping.com/'},
			{'name' : '高朋团购', 'url' : 'http://www.gaopeng.com/'},
			{'name' : 'F　团', 'url' : 'http://www.ftuan.com/'},
			{'name' : '窝窝团', 'url' : 'http://www.55tuan.com/'},
			{'name' : '聚划算', 'url' : 'http://ju.taobao.com/'},
			{'name' : '满座网', 'url' : 'http://www.manzuo.com/'},
			{'name' : '爽　团', 'url' : 'http://www.shuangtuan.com/'},
			{'name' : '米奇网', 'url' : 'http://www.miqi.cn/'},
			{'name' : '爱帮团', 'url' : 'http://tuan.aibang.com/'},
			{'name' : '美丽说', 'url' : 'http://www.meilishuo.com/tuan/'},
			{'name' : '可可团', 'url' : 'http://www.cocotuan.com/'},
			{'name' : '犀利团', 'url' : 'http://www.xilituan.com/'},
		]
	},
	{	
		'cat' : '体育',
		'class' : 'xzg-sport', 
		'cnt' : [
			{'name' : '新浪体育', 'url' : 'http://sports.sina.com.cn/'},
			{'name' : '搜狐体育', 'url' : 'http://sports.sohu.com/'},
			{'name' : '腾讯体育', 'url' : 'http://sports.qq.com/'},
			{'name' : '网易体育', 'url' : 'http://sports.163.com/'},
			{'name' : 'TOM体育', 'url' : 'http://sports.tom.com/'},
			{'name' : '雅虎体育', 'url' : 'http://sports.cn.yahoo.com/'},
			{'name' : 'ESPN中文网', 'url' : 'http://www.espnstar.com.cn/'},
			{'name' : 'cctv5', 'url' : 'http://sports.cntv.cn/'},
			{'name' : '直播吧', 'url' : 'http://www.zhibo8.com/'},
			{'name' : '凤凰体育', 'url' : 'http://news.ifeng.com/sports/'},
			{'name' : '华体网', 'url' : 'http://www.sportscn.com/'},
			{'name' : '体坛周报', 'url' : 'http://www.titan24.com/'},
			{'name' : 'NBA中国', 'url' : 'http://china.nba.com/'},
			{'name' : '新浪NBA', 'url' : 'http://sports.sina.com.cn/nba/'},
			{'name' : '腾讯NBA', 'url' : 'http://sports.qq.com/nba/'},
			{'name' : '网易NBA', 'url' : 'http://sports.163.com/nba/'},
			{'name' : '搜狐NBA', 'url' : 'http://sports.sohu.com/nba.shtml'},
			{'name' : '中国篮协', 'url' : 'http://www.cba.gov.cn/'},
			{'name' : '新浪足球', 'url' : 'http://sports.sina.com.cn/global/'},
			{'name' : '搜狐足球', 'url' : 'http://sports.sohu.com/guojizuqiu.shtml'},
			{'name' : '腾讯足球', 'url' : 'http://sports.qq.com/isocce/'},
			{'name' : 'ESPN足球', 'url' : 'http://www.espnstar.com.cn/new/international/'},
			{'name' : '网易足球', 'url' : 'http://sports.163.com/world/'},
			{'name' : '天下足球网', 'url' : 'http://www.qxzqw.com/'}
		]
	},
	{	
		'cat' : '游戏',
		'class' : 'xzg-game', 
		'cnt' : [
			{'name' : '4399小游戏', 'url' : 'http://www.4399.com/'},
			{'name' : '7K7K小游戏', 'url' : 'http://www.7k7k.com/'},
			{'name' : '3366小游戏', 'url' : 'http://www.3366.com/'},
			{'name' : '2144小游戏', 'url' : 'http://www.2144.cn/'},
			{'name' : '007小游戏', 'url' : 'http://www.yx007.com/'},
			{'name' : '3839小游戏', 'url' : 'http://www.3839.com/'},
			{'name' : '洛克王国', 'url' : 'http://17roco.qq.com/'},
			{'name' : '赛尔号', 'url' : 'http://www.51seer.com/'},
			{'name' : '奥拉星', 'url' : 'http://www.9aola.com/'},
			{'name' : '摩尔庄园', 'url' : 'http://www.51mole.com/'},
			{'name' : '龙斗士', 'url' : 'http://www.9lds.com/'},
			{'name' : '奥雅之光', 'url' : 'http://www.9aoya.com/'},
			{'name' : '穿越火线', 'url' : 'http://cf.qq.com/'},
			{'name' : '地下城与勇士', 'url' : 'http://dnf.qq.com/'},
			{'name' : '七雄争霸', 'url' : 'http://7.qq.com/'},
			{'name' : '英雄之城', 'url' : 'http://yxzc.qq.com/'},
			{'name' : '烽火战国', 'url' : 'http://zg.qq.com/'},
			{'name' : '英雄联盟', 'url' : 'http://lol.qq.com/'},
			{'name' : '冒险岛', 'url' : 'http://mxd.sdo.com/'},
			{'name' : '热血传奇', 'url' : 'http://mir2.sdo.com/'},
			{'name' : '彩虹岛', 'url' : 'http://chd.sdo.com/homepage.asp'},
			{'name' : '仙境传说', 'url' : 'http://ro.sdo.com/'},
			{'name' : '龙之谷', 'url' : 'http://dn.sdo.com/'},
			{'name' : '苍天OL', 'url' : 'http://ct.sdo.com/'},
			{'name' : '劲舞团', 'url' : 'http://mg.9you.com/'},
			{'name' : '仙剑奇侠传', 'url' : 'http://xj.9you.com/'},
			{'name' : '神兵传奇', 'url' : 'http://sc.9you.com/'},
			{'name' : '光线飞车', 'url' : 'http://rc.9you.com/'},
			{'name' : '宠物森林', 'url' : 'http://mf.9you.com/'},
			{'name' : '流星蝴蝶剑', 'url' : 'http://lx.9you.com/'},
			{'name' : '梦幻西游', 'url' : 'http://xyq.163.com/'},
			{'name' : '大唐无双', 'url' : 'http://dt2.163.com/'},
			{'name' : '天下3', 'url' : 'http://tx3.163.com/'},
			{'name' : '魔兽世界', 'url' : 'http://www.warcraftchina.com/'},
			{'name' : '倩女幽魂OL', 'url' : 'http://qn.163.com/'},
			{'name' : '藏宝阁', 'url' : 'http://cbg.163.com/'},
			{'name' : '梦幻诛仙', 'url' : 'http://xmhzx.wanmei.com/'},
			{'name' : '完美世界', 'url' : 'http://world2.wanmei.com/'},
			{'name' : '口袋西游', 'url' : 'http://kdxy.wanmei.com/'},
			{'name' : '赤壁', 'url' : 'http://chibi.wanmei.com/'},
			{'name' : '神鬼传奇', 'url' : 'http://sgcq.wanmei.com/'},
			{'name' : '降龙之剑', 'url' : 'http://xlzj.wanmei.com/'},
		]
	},
	{	
		'cat' : '音乐',
		'class' : 'xzg-music', 
		'cnt' : [
			{'name' : '虾　米', 'url' : 'http://www.xiami.com/'},
			{'name' : '巨　鲸', 'url' : 'http://www.top100.cn/'},
			{'name' : '酷　我', 'url' : 'http://mbox.kuwo.cn/'},
			{'name' : '百度MP3', 'url' : 'http://mp3.baidu.com/'},
			{'name' : 'ting!', 'url' : 'http://ting.baidu.com/'},
			{'name' : 'QQ音乐', 'url' : 'http://music.qq.com/'},
			{'name' : '酷　狗', 'url' : 'http://www.kugou.com/'},
			{'name' : '九　天', 'url' : 'http://www.9sky.com/'},
			{'name' : 'DJ嗨嗨', 'url' : 'http://www.djkk.com/'},
			{'name' : '深港DJ', 'url' : 'http://www.ik123.com/'},
			{'name' : 'DJ音乐厅', 'url' : 'http://www.hcdj.com/'},
			{'name' : 'DJ527', 'url' : 'http://www.dj527.com/'},
			{'name' : '音悦台', 'url' : 'http://www.yinyuetai.com/'},
			{'name' : '优酷音乐', 'url' : 'http://music.youku.com/'},
			{'name' : '土豆音乐', 'url' : 'http://music.tudou.com/'},
			{'name' : '酷6音乐', 'url' : 'http://mv.ku6.com/'},
			{'name' : '百度音乐MV', 'url' : 'http://video.baidu.com/childchannal/videomv/videomv.html'},
			{'name' : '奇艺音乐', 'url' : 'http://www.qiyi.com/yinyue/'},
			{'name' : '儿童专辑', 'url' : 'http://list.mp3.baidu.com/top/shaoergequ.html'},
			{'name' : '经典老歌', 'url' : 'http://mp3.baidu.com/m?f=ms&rf=idx&tn=baidump3&ct=134217728&lf=&rn=&word=%BE%AD%B5%E4%C0%CF%B8%E8&lm=-1&rf=bangdang#1'},
			{'name' : '影视金曲', 'url' : 'http://list.mp3.baidu.com/top/movie.html'},
			{'name' : '轻音乐', 'url' : 'http://list.mp3.baidu.com/top/qingyinyue.html'},
			{'name' : '网络歌曲', 'url' : 'http://mp3.baidu.com/m?f=ms&rf=idx&tn=baidump3&ct=134217728&lf=&rn=&word=%CD%F8%C2%E7%B8%E8%C7%FA&lm=-1rf=bangdang#1'},
			{'name' : '日韩流行', 'url' : 'http://list.mp3.baidu.com/top/rihan.html'},
			{'name' : '音乐之声', 'url' : 'http://musicradio.cnr.cn/'},
			{'name' : '豆瓣电台', 'url' : 'http://douban.fm/'},
			{'name' : '青檬音悦台', 'url' : 'http://www.911pop.com/'},
			{'name' : '多米音乐', 'url' : 'http://www.duomi.com/'},
			{'name' : '亦　歌', 'url' : 'http://www.1g1g.com/'},
			{'name' : '新浪乐库', 'url' : 'http://music.sina.com.cn/yueku/'}
		]
	},
	{	
		'cat' : '极客',
		'class' : 'xzg-geek', 
		'cnt' : [
			{'name' : 'Engadget', 'url' : 'http://cn.engadget.com/'},
			{'name' : '爱极客', 'url' : 'http://www.igeek.com.cn/'},
			{'name' : '36氪', 'url' : 'http://www.36kr.com/'},
			{'name' : '互动中国', 'url' : 'http://www.damndigital.com/'},
			{'name' : 'cnbeta', 'url' : 'http://www.cnbeta.com/'},
			{'name' : '远景', 'url' : 'http://www.pcbeta.com/'},
			{'name' : '麦根', 'url' : 'http://nmag.cn/'},
			{'name' : '极客公园', 'url' : 'http://event.geekpark.net/'},
			{'name' : '动点科技', 'url' : 'http://cn.technode.com/'},
			{'name' : 'Tech2IPO', 'url' : 'http://tech2ipo.com/'},
			{'name' : '爱PC', 'url' : 'http://www.ipc.me/'},
			{'name' : '威锋网', 'url' : 'http://www.weiphone.com/'},
			{'name' : '云诺', 'url' : 'http://www.yun.io/'}

		]
	},
]



